### PR TITLE
MITRE STIX object "Campaign" added

### PR DESCRIPTION
**Pull request by arnavdas88**
Signed-off-by: Arnav Das <arnav.das88@gmail.com>

### CODE REVIEW

**Comment by arnavdas88** [comment]
This PR is concerning the Issue [#125](https://github.com/swimlane/pyattck/issues/125). I have added the **Campaign** class that gets populated from the new data

**Comment by arnavdas88** [comment]
@MSAdministrator ?

**Comment by adamcysec** [comment]
Code looks good! I can confirm fixes Pyattck issue [#125](https://github.com/swimlane/pyattck/issues/125).

**Comment by arnavdas88** [comment]
@MSAdministrator ?

**Comment by SirSkizo** [comment]
@MSAdministrator @arnavdas88  any new about this MR?

**Comment by MSAdministrator** [comment]
@brantw is it possible to give me access to this repository so I can merge this open PR? I’ll need pyattck repo as well.

**Comment by MSAdministrator** [comment]
@brantw thank you!

@arnavdas88 @adamcysec @SirSkizo i’m going to merge this but I won’t be able to fully integrate the change into pyattck until tomorrow. 

Thanks for creating this PR and for all the support and work!

**Comment by arnavdas88** [comment]
Thank you @MSAdministrator 😊

**Comment by arnavdas88** [comment]
Any Update @MSAdministrator ?

**Pull request merged**
