### PR TITLE
inf-3481: Move AWS role to actions secret

### PR DESCRIPTION
**Pull request by larntz**
Moving this role arn to a repo secret.

### CODE REVIEW

**Comment by larntz** [comment]
@MSAdministrator Requesting your review on this because you approved the last change to this code by our team. 

Security would like this role to be moved into a repo secret. When looking at this I also noticed this workflow has failed the last few times it's run and wanted to make you aware of that.

**Review by MSAdministrator — COMMENTED** [review]
Good with me

**Comment by MSAdministrator** [comment]
@larntz Hey Luke, I cannot seem to access the URLs (within the README) from S3 anymore from my browser. Did you or anyone else change this behavior? Currently `pyattck` is broken because of this.

**Comment by larntz** [comment]
I did not make any changes to this bucket. I'll see what I can find out.

**Comment by MSAdministrator** [comment]
@larntz Thanks so much! Based on my limited knowledge (and based on when issues were filed) it may have happen around April 3rd or somewhere around there.

**Comment by larntz** [comment]
Thanks for the additional info.

**Pull request merged**
